### ISSUE TITLE
Missing dependencies on installation

### ISSUE THREAD

**Issue by vschroeter** [vschroeter/rosmetasys#1]
Originally posted here: ~/ros2/ros2_ws/src$ rosmetasys export -i
Traceback (most recent call last):
File "/home/jm/.local/bin/rosmetasys", line 5, in
from rosmetasys.cli import cli
File "/home/jm/.local/lib/python3.10/site-packages/rosmetasys/cli.py", line 4, in
from click_aliases import ClickAliasedGroup
ModuleNotFoundError: No module named 'click_aliases'

Tried it with iron on ubuntu 22.04.

**Comment by vschroeter** [comment]
Fixed in 6caaec6
